version: '3'
services:
  hyperf:
    container_name: hyperf
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    depends_on:
      - mysql
      - redis
    networks:
      - clean-architecture
  
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: project
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - clean-architecture
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKV
    networks:
      - clean-architecture

networks:
  clean-architecture:
    driver: bridge
